grants:
  default: "PLAYER"
  immortal: "IMMORTAL"
  mythices: "MYTHICES"
  visitor: "VISITOR"
  wizard: "WIZARD"
  champion: "CHAMPION"
  merchant: "MERCHANT"
  netherite: "NETHERITE"
  ender: "ENDER"

grant_priorities:
  - default;0
  - immortal;1
  - mythices;2
  - visitor;3
  - wizard;4
  - champion;5
  - merchant;6
  - netherite;7
  - ender;8

limits:
  ender:
    immortal: 3
    visitor: 2
    merchant: 2
    champion: 1
    mythices: 1
